Drop down values
getgauge/taiko pull request #1563
Opened 2020-10-01 09:08 UTC by saikrishna321

2020-10-01 09:28 UTC, NivedhaSenthil commented
I feel this can be named `options` instead of `values` as value is generally linked to selected option of the dropdown.

2020-10-01 10:25 UTC, zabil commented
> I feel this can be named `options` instead of `values` as value is generally linked to selected option of the dropdown.

Ah yes, I agree. `options` is the right name for this API and how users refer to it.

2020-10-01 14:29 UTC, zabil commented
>  I feel this can be named `options` instead of `values` as value is generally linked to selected option of the dropdown.

@saikrishna321 ran into an issue with the name `options` this is because 

https://github.com/getgauge/taiko/blob/c082b8c4060cbab4484d3741fae9c55da95d0725/lib/elementWrapper/elementWrapper.js#L27-L30

sets the `options` variable so calling `dropDown({ id: 'select' }).options()` will refer to `this.options` variable instead. We should either change `const { selector, options } = prepareParameters(attrValuePairs, _options, ...args); ` to something else or call the method `dropDown({ id: 'select' }).valueOptions()`

2020-10-02 08:34 UTC, zabil requested changes

2020-10-02 08:34 UTC, zabil commented on lib/taiko.js
> + * await dropDown('Vehicle:').values() - Returns all the values from the drop down
shouldn't this be 
```suggestion
 * await dropDown('Vehicle:').options() - Returns all available options from the drop down
```

2020-10-02 08:34 UTC, zabil commented on lib/elements/dropDown.js
> +    function getValues() {
```suggestion
    function getOptions() {
```

2020-10-02 08:34 UTC, zabil commented on lib/elements/dropDown.js
> +    const { result } = await this.runtimeHandler.runtimeCallFunctionOn(getValues, null, {
```suggestion
    const { result } = await this.runtimeHandler.runtimeCallFunctionOn(getOptions, null, {
```

2020-10-02 08:34 UTC, zabil commented on test/unit-tests/dropDown.test.js
> +    it('test values()', async () => {
```suggestion
    it('test options()', async () => {
```

2020-10-02 13:55 UTC, zabil approved these changes

2020-10-02 14:11 UTC, merged