openTab - incognito window
getgauge/taiko pull request #1573
Opened 2020-10-05 02:19 UTC by saikrishna321

Address #1572 #1282 

Signed-off-by: saikrishna321 <saikrishna321@yahoo.com>

2020-10-05 11:28 UTC, zabil commented
I did one round of testing with the following. 

```
const { openBrowser, goto, openTab, openIncognitoWindow, closeTab, closeIncognitoWindow, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('google.com');
        await openTab('github.com');
        await openIncognitoWindow({name: 'gauge'});
        await goto('gauge.org');
        await openTab('taiko.dev');
        await closeTab();
        await closeIncognitoWindow('gauge');
        await closeTab();
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

It looks good so far, will try more combinations.

2020-10-05 11:44 UTC, saikrishna321 commented
@zabil Thanks for looking at it! `await openIncognitoWindow({name: 'gauge'})` is an Incognito window with a tab name `gauge` so when users says `switchTo({name: 'gauge')` it switches to tab and not to the window. With that `await closeIncognitoWindow('gauge');` will close the tab {name: 'gauge'} and not the entire window. Looking into how to fix this. @NivedhaSenthil pointed me to use different API. 


Try scenario's by opening two IncognitoWindow and play around with openTab and switchTo

2020-10-06 14:49 UTC, zabil requested changes
Script

```
const { openBrowser, goto, openTab, openIncognitoWindow, switchTo, closeTab, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('google.com');
        await openTab('github.com', { name: 'github'});
        await openIncognitoWindow({name: 'gauge'});
        await openTab('github.com', { name: 'github2'});
        await switchTo(/github/);
        await switchTo({name: 'github'});
        await closeTab();
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

The `closeTab` at the end of the script close the last tab on the incognito window instead of the tab that it switched to on the main window.

2020-10-09 04:50 UTC, NivedhaSenthil requested changes

2020-10-09 04:50 UTC, NivedhaSenthil commented on lib/taiko.js
> +    await dom.getDocument();
we dont need`dom.getDocument()` anymore as we use objectID instead of nodeID

2020-10-10 01:12 UTC, saikrishna321 commented
@zabil @NivedhaSenthil `closeTab` API currently closed all the matching tabs with given identifier. Should we only close the current active tab. 

For example: 

`
await openBrowser();
        await goto('google.com');
        await openTab('github.com', { name: 'github'});
        await openTab('github.com', { name: 'github1'});
        await closeTab(); // This will close both the github.com tabs. I'm expecting the tab with name github1 should only be closed.
`

2020-10-12 07:26 UTC, NivedhaSenthil commented
I feel the current behavior is correct.. if user wants to close the active tab they can simply say `closeTab()` when an URL is explicitly passed I would expect Taiko to close all the tabs matching the URL

2020-10-12 07:30 UTC, NivedhaSenthil commented
Also corresponding to above comment.. I would expect the below code to close only the active tab and not both the tabs matching `gauge.org` ...its closing all the matching tabs with the changes in PR

```
(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await openTab("gauge.org");
        await openTab("gauge.org");
        await closeTab();
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

2020-10-22 02:44 UTC, NivedhaSenthil commented
closing in favor of #1617

2020-10-22 02:44 UTC, closed without merging