Fix 1624
getgauge/taiko pull request #1655
Opened 2020-11-01 16:44 UTC by saikrishna321

Address #1624

2020-11-04 15:34 UTC, zabil requested changes

2020-11-04 15:34 UTC, zabil commented on lib/elementWrapper/textBoxWrapper.js
> +  const matchingPlaceHolders = [...searchElement.querySelectorAll('input')].filter((labelElem) => {
The method can be renamed from `getTextBoxElementWithLabel` to `getTextBoxElementWithLabelOrPlaceholder`

2020-11-04 15:34 UTC, zabil commented on test/unit-tests/textBox.test.js
> +                            <input type="${inputType.type}" placeholder='Filter'/>
Can we have a separate input element with only the placeholder for the test?  I notice that this input is used for wrapped label test.

2020-11-04 17:21 UTC, saikrishna321 commented
@zabil @NivedhaSenthil ping

2020-11-04 18:46 UTC, zabil commented
I added a few comments

2020-11-05 09:39 UTC, zabil commented on test/unit-tests/textBox.test.js
> +      <p>Click the button to change the placeholder text of the search field.</p>
Is this section and the `<script>` part required? The tests don't see to use them

2020-11-09 10:50 UTC, zabil commented
@saikrishna321 was going to test this. But before that just wanted to check if this will work if the input element is inside a shadow dom. I don't see anything specific to cover that condition.

2020-11-10 09:47 UTC, zabil approved these changes
Tested, all is good. Marked this as release candidate. 
Also noticed that the DCO may not be signed on one of the commits.

2020-11-11 07:24 UTC, merged